apache/aurora

build-support/python/make-pycharm-virtualenv

With modern PyCharm (2018+), virtualenv support for wheels and namespace
packages works, so kill the obsolete `--egg` in our pip installs. Also
leverage `./pants options` to grab the appropriate `pytest`
requirements.

Fixup the pycharm setup script.

---

build-support/release/release-candidate

According to new Apache policy, we should only distribute a SHA-256 or SHA-512 checksum along with new releases.
Removing MD5 hash from releases as required by new Apache policy in preparation for 0.21.0 release.
Making SHA-512 our default checksum for releases.

Removing MD5 checksum and making SHA-512 our default release checksum

---

build-support/release/release
build-support/release/release-candidate
build-support/release/verify-release-candidate

No longer needed as Apache policy recommends at least SHA-256

Removing MD5 check from verify release candidate script and release script

---

src/main/python/apache/aurora/executor/common/sandbox.py
src/main/python/apache/aurora/executor/thermos_task_runner.py
src/main/python/apache/thermos/core/process.py
src/main/python/apache/thermos/runner/thermos_runner.py
src/test/python/apache/aurora/executor/common/test_sandbox.py
src/test/sh/org/apache/aurora/e2e/test_end_to_end.sh

This change makes Aurora compatible with Mesos 1.6.0 which has changed the permission of sandbox folders (see https://issues.apache.org/jira/browse/MESOS-8332).
Please have a look at the individual commits for further details and descriptions.

 Fix sandbox permission errors with Mesos 1.6.0 

---

build-support/python/make-mesos-native-egg

Addressing #39 en route to #38.
Tested all distros. CentOS6 is broken but it was also broken when using a vagrantbox. It is a candidate for removal unless someone wants to dedicate time to figuring out what's wrong and fixing it.
Moving this process to Docker speeds up the process of generating Mesos eggs.

Move Mesos Egg generation from Vagrant to Docker

---

src/main/python/apache/aurora/client/cli/context.py
src/main/python/apache/aurora/client/config.py
src/main/python/apache/aurora/config/__init__.py
src/main/python/apache/aurora/config/loader.py
src/test/python/apache/aurora/config/BUILD
src/test/python/apache/aurora/config/test_loader.py

Problem: when reusing the aurora.client.cli.context to process multiple jobkeys from a config_file, the client currently reloads and processes the config file for each jobkey. For large complicated aurora files this can take ~40s to process which makes it expensive to do this every time for each jobkey.
Solution: memoize the loader.load() on the config file path so that we only load and process each config file once.
Result:  We only need to load and process each config file once.  For config files with ~50keys and a 40s load time, this significantly reduces the overall time spent inspecting the jobs.

Memoize loader.load and loader.load_json

---

build-support/python/make-mesos-native-egg

Usage http://mirror.centos.org/centos/6/sclo/x86_64/rh/devtoolset-7/

Change devtoolset-7 (scl-rh) of CentOS6

---

src/main/java/org/apache/aurora/scheduler/thrift/ReadOnlySchedulerImpl.java
src/test/java/org/apache/aurora/scheduler/thrift/ReadOnlySchedulerImplTest.java
ui/src/main/js/components/TaskListItemActions.js

With this patch two things are done:
1. The executor name is exposed through the getTasksWithoutConfigs API. This is necessary for the UI to distinguish between Thermos based executors which expect a certain sandbox layout, and non-thermos based executors which do not have this concept.
This adds minimal overhead (in the case of thermos constant overhead) and doesn't reveal any more information than was previously known or obtainable through the getTaskStatus.
2. Renders links to the thermos observer only if the executor used is thermos.
Used a bold tag when non-thermos tasks are rendered for the Mesos agent address in order to maintain UI consistency.

Custom executor UI fix

---

3rdparty/python/requirements.txt
src/test/python/apache/aurora/config/test_base.py

This fixes a few inconsistencies with hashing and equality https://github.com/wickman/pystachio/pull/30. This is not directly applicable for Aurora but will be for downstream packages that try to consume schema definitions in Python 3. In any case, I have added a test to explicitly cover the assumptions in Aurora.

Update Pystachio to 0.8.4

---

3rdparty/python/BUILD
RELEASE-NOTES.md
Vagrantfile
build-support/packer/build.sh
build.gradle
src/main/python/apache/aurora/executor/common/sandbox.py

* Upgraded Mesos dependencies to 1.6.1
* Uploaded apache-aurora/dev-environment 0.0.17 up to Vagrant Cloud
* Upgraded Docker2ACI to latest version.
* Upgraded go to latest version and changed download location to match recent changes by Google.
Mesos Info:
* Mesos 1.6 changelog: https://mesos.apache.org/blog/mesos-1-6-1-released/
* Mesos update instructions: https://mesos.apache.org/documentation/latest/upgrades/#upgrading-from-1-5-x-to-1-6-x
Testing done:
* Ran integration tests

Upgrade dev enviornment to Mesos 1.6.1

---

src/main/java/org/apache/aurora/scheduler/TierInfo.java
src/main/java/org/apache/aurora/scheduler/configuration/ConfigurationManager.java
src/main/java/org/apache/aurora/scheduler/storage/durability/ThriftBackfill.java
src/test/java/org/apache/aurora/scheduler/base/TaskTestUtil.java
src/test/java/org/apache/aurora/scheduler/storage/durability/ThriftBackfillTest.java

isProd is a field inside the Job Configuration that was deprecated a long time ago (Aurora 0.14.0) when tiers were introduced. However, its usage in the code base [remains](https://github.com/apache/aurora/blob/master/src/main/java/org/apache/aurora/scheduler/quota/QuotaManager.java#L81).
Previously we relied on backfill to find a tier similar to the job's specifications (looked for a match in preemption and recovable).
This patch seeks to explicitly set default tier (specified in the `tiers.json` file) and add an `isProduction()` method to the `TierInfo`. The `isProduction()` field returns true only if the tier is non-revocable and not preemtable.
The patch also removes the backfill code which should not be necessary at this point.
End to end
Integration tests

Set IsProd in Scheduler

---

.isort.cfg
pants.ini
src/main/python/apache/aurora/admin/aurora_admin.py
src/main/python/apache/aurora/client/api/updater_util.py
src/main/python/apache/aurora/config/__init__.py
src/main/python/apache/aurora/config/loader.py
src/main/python/apache/aurora/config/thrift.py
src/main/python/apache/thermos/monitoring/process_collector_psutil.py
src/test/python/apache/aurora/client/api/test_updater_util.py
src/test/python/apache/aurora/client/test_config.py
src/test/python/apache/aurora/config/test_loader.py
src/test/python/apache/aurora/config/test_thrift.py
src/test/python/apache/aurora/executor/common/test_announcer.py

Two workaround for the failing build. Both are caused by improperly pinned dependencies of our testing infrastructure. 
* Use pytest version with Python 2 compatible requirements
* Resort according to latest isort release

Fix failing build

---

.travis.yml
build-support/thrift/thriftw
pants
pants.ini
src/main/python/apache/aurora/admin/aurora_admin.py
src/main/python/apache/aurora/client/base.py
src/main/python/apache/aurora/client/cli/client.py
src/main/python/apache/aurora/client/cli/jobs.py
src/main/python/apache/aurora/client/config.py
src/main/python/apache/aurora/config/resource.py
src/main/python/apache/aurora/tools/java/organize_imports.py
src/main/python/apache/thermos/common/path.py
src/main/python/apache/thermos/monitoring/detector.py
src/test/python/apache/aurora/client/test_binding_helper.py
src/test/python/apache/aurora/common/test_clusters.py
src/test/python/apache/aurora/executor/common/test_health_checker.py
src/test/python/apache/aurora/executor/test_thermos_task_runner.py
src/test/python/apache/thermos/cli/test_common.py

This brings us to the most recent Pants version and updates a few related requirements along the way.
* Update to Pants 1.15.0. This requires a few code adjustment due to a more recent style checker
* Update to latest virtualenv for installing Python helpers
* Run Travis tests on Xenial, in line with our Vagrant environment
The following passed as expected
```
$ rm -rf ~/.cache/pants/
$ ./build-support/jenkins/build.sh
```
additionally, the following also passed
```
$ vagrant destroy
$ vagrant up
```

Upgrade Pants

---

src/main/python/apache/thermos/config/schema_helpers.py

This fixes 2 errors in the `schema_helpers.py` file to make the code Python 3 compatible.
* `reduce` was moved to `functools` and [this was backported with Python 2.6](https://docs.python.org/2.7/library/functools.html#functools.reduce).
* Replace `map` with a list comprehension, as it now returns a generator.

Make schema_helpers.py python3 compatible

---

RELEASE-NOTES.md
docs/reference/observer-configuration.md
src/main/python/apache/aurora/config/BUILD
src/main/python/apache/aurora/tools/thermos_observer.py
src/main/python/apache/thermos/monitoring/resource.py
src/main/python/apache/thermos/observer/task_observer.py
src/test/python/apache/thermos/monitoring/test_resource.py

Add observer command line option `--disable_task_resource_collection` to disable the collection of CPU, memory, and disk metrics for observed tasks. This is useful in setups where metrics cannot be gathered reliable (e.g. when using PID namespaces) or when it is expensive due to hundreds of active tasks per host.
Sometimes the hosts are also tightly packed with many small tasks (e.g. ~130 active tasks and ~1000 finished tasks). Even with very relaxed scrape settings of  `--task_process_collection_interval_secs=3000` and `--task_disk_collection_interval_secs=3000` it can take between 150ms-2500ms to render the observer landing page `/main`. This patch reduces this to about 100ms-150ms. 
There is no immediate downside as metrics reporting is broken anyway due to the PID namespacing: We are …

Add observer flag to disable resource metric collection

---

src/main/java/org/apache/aurora/scheduler/sla/SlaManager.java
src/main/java/org/apache/aurora/scheduler/sla/SlaModule.java
src/test/java/org/apache/aurora/scheduler/config/CommandLineTest.java
src/test/java/org/apache/aurora/scheduler/sla/SlaManagerTest.java

* Allows operators to enable SLA aware killing for non production workloads. This is turned off by default. More details can be found in the issue raised #62 
- End to end
- Unit testing

Adding flag to enable SLA aware killing for non production workloads.

---

RELEASE-NOTES.md
docs/reference/scheduler-configuration.md
src/main/java/org/apache/aurora/scheduler/app/SchedulerMain.java

* Updated RELEASE-NOTES with information about the new flag which allows operators to enable SLA aware killing for non-production tasks.
* Fixed a typo in SchedulerMain.
* Updated documentation to reflect the output of the scheduler when run with the `-help` flag.
Documentation change.

Updating relese notes and scheduler documentation

---

src/main/java/org/apache/aurora/scheduler/app/AppModule.java
src/main/java/org/apache/aurora/scheduler/configuration/ConfigurationManager.java
src/test/java/org/apache/aurora/scheduler/base/TaskTestUtil.java
src/test/java/org/apache/aurora/scheduler/configuration/ConfigurationManagerTest.java
src/test/java/org/apache/aurora/scheduler/thrift/ThriftIT.java

Missed this on the original patch to enable SLA aware killing for non-prod jobs.
Currently the flag that enable non-production jobs to be drained with an SLA policy does not also allow jobs that are non production to have an SLA Policy object attached to them.
This patch modifies ConfigurationManager to allow non-production jobs to have an SLA policy attached to them.
Added a unit test to make sure the flag is working as expected.
* End to end
* Unit testing

Allow configuration manager to accept non-prod jobs with SLAPolicy

---

src/test/sh/org/apache/aurora/e2e/http/http_example.aurora

Docker based tasks need a bit more time to come up successfully. This change allows end to end tests that were previously failing to pass.
End to end tests

Increasing initial timeout for health check in end to end

---

src/test/sh/org/apache/aurora/e2e/test_kerberos_end_to_end.sh

Kerberos tests are currently flaky because the mit keyring server is often unavailable. Changing keyring servers to the ubuntu one.
Adding variable which sets locale in order to satisfy new requirements by pants.
End to end

Fixing kerberos end to end tests

---

src/main/java/org/apache/aurora/scheduler/updater/JobUpdateControllerImpl.java
src/main/java/org/apache/aurora/scheduler/updater/SideEffect.java
src/main/java/org/apache/aurora/scheduler/updater/Updates.java
src/test/java/org/apache/aurora/scheduler/updater/JobUpdaterIT.java

Previously there was a bug where one of the instances would not be updated before the pause kicked in. This resulted in a weird state for the update where the straggler instances (the last instance to enter a terminal state) was not evaluated until the resume was triggered.
This PR fixes this issue along with removing the final acknowledgement pause when the update as a whole has entered a terminal state. I removed this because it doesn't make much sense to pause right before the update enters a terminal state because we have other mechanisms to handle that and it complicates the code unnecessarily. If the community disagrees the feature can be added later.
Code Quality
Integration
End to End

Batch Auto Pause improvements

---

build-support/python/make-mesos-native-egg

* Dropping support for generating Mesos eggs for Trusty since it is now EOL and it has also been dropped from our packaging.
* Upgrading Jessie to Stretch since Jessie has also reached EOL.
* Generated the eggs and used them to build packages.

Dropping support for making Trusty eggs. Upgrading Jessie to Stretch.
